// src/app/head.tsx
export default function Head() {
    return (
      <>
        <title>Pet Finder</title>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }
  